# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/normUI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(509, 618)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("selection-color: rgb(255, 255, 255);")
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("background-color: rgb(54, 57, 63);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.app_tab = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_tab.sizePolicy().hasHeightForWidth())
        self.app_tab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.app_tab.setFont(font)
        self.app_tab.setMouseTracking(False)
        self.app_tab.setStyleSheet("\n"
"QTabBar::tab, \n"
"QTabBar::tab:hover\n"
"{\n"
"border: 1px solid rgba(105, 118, 132, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(98, 114, 164);\n"
"background-color: rgb(47, 49, 54);\n"
"}\n"
"\n"
"")
        self.app_tab.setElideMode(QtCore.Qt.ElideLeft)
        self.app_tab.setDocumentMode(True)
        self.app_tab.setTabsClosable(False)
        self.app_tab.setMovable(False)
        self.app_tab.setObjectName("app_tab")
        self.main_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_tab.sizePolicy().hasHeightForWidth())
        self.main_tab.setSizePolicy(sizePolicy)
        self.main_tab.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.main_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_tab.setStyleSheet("background-color: rgb(54, 57, 63);")
        self.main_tab.setObjectName("main_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.episodeline_Vlayout = QtWidgets.QVBoxLayout()
        self.episodeline_Vlayout.setObjectName("episodeline_Vlayout")
        self.episode_line = QtWidgets.QLineEdit(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.episode_line.sizePolicy().hasHeightForWidth())
        self.episode_line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.episode_line.setFont(font)
        self.episode_line.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"padding-bottom:7px;")
        self.episode_line.setObjectName("episode_line")
        self.episodeline_Vlayout.addWidget(self.episode_line)
        self.gridLayout_2.addLayout(self.episodeline_Vlayout, 8, 1, 1, 2)
        self.header_buttons_Hlayout = QtWidgets.QHBoxLayout()
        self.header_buttons_Hlayout.setObjectName("header_buttons_Hlayout")
        self.rickroll_button = QtWidgets.QPushButton(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rickroll_button.sizePolicy().hasHeightForWidth())
        self.rickroll_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.rickroll_button.setFont(font)
        self.rickroll_button.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.rickroll_button.setObjectName("rickroll_button")
        self.header_buttons_Hlayout.addWidget(self.rickroll_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header_buttons_Hlayout.addItem(spacerItem)
        self.config_save_button = QtWidgets.QPushButton(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_save_button.sizePolicy().hasHeightForWidth())
        self.config_save_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.config_save_button.setFont(font)
        self.config_save_button.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 3px;\n"
"border-top: 1px solid  rgb(37, 40, 44);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 2px solid  rgb(37, 40, 44);\n"
"font: 75 14pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-top: 1px solid  rgb(37, 40, 44);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 2px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 2px solid  rgb(37, 40, 44);\n"
"border-bottom: 1px solid  rgb(37, 40, 44);\n"
"padding-top: -5px;\n"
"}")
        self.config_save_button.setObjectName("config_save_button")
        self.header_buttons_Hlayout.addWidget(self.config_save_button)
        self.gridLayout_2.addLayout(self.header_buttons_Hlayout, 2, 1, 1, 2)
        self.footer_buttons_Hlayout = QtWidgets.QHBoxLayout()
        self.footer_buttons_Hlayout.setObjectName("footer_buttons_Hlayout")
        self.FAQ_open_button = QtWidgets.QPushButton(self.main_tab)
        self.FAQ_open_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FAQ_open_button.sizePolicy().hasHeightForWidth())
        self.FAQ_open_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.FAQ_open_button.setFont(font)
        self.FAQ_open_button.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 12pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-bottom: none;\n"
"padding-top: -5px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/ICONS/faq_question_icon_149479.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FAQ_open_button.setIcon(icon)
        self.FAQ_open_button.setObjectName("FAQ_open_button")
        self.footer_buttons_Hlayout.addWidget(self.FAQ_open_button)
        self.anibaza_site_open_button = QtWidgets.QPushButton(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anibaza_site_open_button.sizePolicy().hasHeightForWidth())
        self.anibaza_site_open_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.anibaza_site_open_button.setFont(font)
        self.anibaza_site_open_button.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 12pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-bottom: none;\n"
"padding-top: -5px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/ICONS/web_120072.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.anibaza_site_open_button.setIcon(icon1)
        self.anibaza_site_open_button.setObjectName("anibaza_site_open_button")
        self.footer_buttons_Hlayout.addWidget(self.anibaza_site_open_button)
        self.hardsub_folder_open_button = QtWidgets.QPushButton(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hardsub_folder_open_button.sizePolicy().hasHeightForWidth())
        self.hardsub_folder_open_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.hardsub_folder_open_button.setFont(font)
        self.hardsub_folder_open_button.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 12pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-bottom: none;\n"
"padding-top: -5px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/ICONS/folder_storage_file_icon_193553.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hardsub_folder_open_button.setIcon(icon2)
        self.hardsub_folder_open_button.setObjectName("hardsub_folder_open_button")
        self.footer_buttons_Hlayout.addWidget(self.hardsub_folder_open_button)
        self.gridLayout_2.addLayout(self.footer_buttons_Hlayout, 16, 1, 2, 2)
        self.app_version_line_Vlayout = QtWidgets.QVBoxLayout()
        self.app_version_line_Vlayout.setObjectName("app_version_line_Vlayout")
        self.app_version_label = QtWidgets.QLabel(self.main_tab)
        self.app_version_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_version_label.sizePolicy().hasHeightForWidth())
        self.app_version_label.setSizePolicy(sizePolicy)
        self.app_version_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.app_version_label.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.app_version_label.setAlignment(QtCore.Qt.AlignCenter)
        self.app_version_label.setWordWrap(False)
        self.app_version_label.setObjectName("app_version_label")
        self.app_version_line_Vlayout.addWidget(self.app_version_label)
        self.gridLayout_2.addLayout(self.app_version_line_Vlayout, 18, 1, 1, 2)
        self.render_control_Hlayout = QtWidgets.QHBoxLayout()
        self.render_control_Hlayout.setObjectName("render_control_Hlayout")
        self.render_settings_Vlayout = QtWidgets.QVBoxLayout()
        self.render_settings_Vlayout.setObjectName("render_settings_Vlayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_settings_Vlayout.addItem(spacerItem1)
        self.render_settings_label = QtWidgets.QLabel(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.render_settings_label.sizePolicy().hasHeightForWidth())
        self.render_settings_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.render_settings_label.setFont(font)
        self.render_settings_label.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.render_settings_label.setAlignment(QtCore.Qt.AlignCenter)
        self.render_settings_label.setObjectName("render_settings_label")
        self.render_settings_Vlayout.addWidget(self.render_settings_label)
        self.logo_check = QtWidgets.QCheckBox(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_check.sizePolicy().hasHeightForWidth())
        self.logo_check.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.logo_check.setFont(font)
        self.logo_check.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.logo_check.setChecked(True)
        self.logo_check.setObjectName("logo_check")
        self.render_settings_Vlayout.addWidget(self.logo_check)
        self.soft_nvenc_check = QtWidgets.QCheckBox(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soft_nvenc_check.sizePolicy().hasHeightForWidth())
        self.soft_nvenc_check.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.soft_nvenc_check.setFont(font)
        self.soft_nvenc_check.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.soft_nvenc_check.setChecked(False)
        self.soft_nvenc_check.setObjectName("soft_nvenc_check")
        self.render_settings_Vlayout.addWidget(self.soft_nvenc_check)
        self.hard_nvenc_check = QtWidgets.QCheckBox(self.main_tab)
        self.hard_nvenc_check.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hard_nvenc_check.sizePolicy().hasHeightForWidth())
        self.hard_nvenc_check.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hard_nvenc_check.setFont(font)
        self.hard_nvenc_check.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;")
        self.hard_nvenc_check.setCheckable(True)
        self.hard_nvenc_check.setChecked(False)
        self.hard_nvenc_check.setObjectName("hard_nvenc_check")
        self.render_settings_Vlayout.addWidget(self.hard_nvenc_check)
        self.render_control_Hlayout.addLayout(self.render_settings_Vlayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.render_control_Hlayout.addItem(spacerItem2)
        self.render_mode_Vlayout = QtWidgets.QVBoxLayout()
        self.render_mode_Vlayout.setObjectName("render_mode_Vlayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_mode_Vlayout.addItem(spacerItem3)
        self.render_mode_label = QtWidgets.QLabel(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.render_mode_label.sizePolicy().hasHeightForWidth())
        self.render_mode_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.render_mode_label.setFont(font)
        self.render_mode_label.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.render_mode_label.setAlignment(QtCore.Qt.AlignCenter)
        self.render_mode_label.setObjectName("render_mode_label")
        self.render_mode_Vlayout.addWidget(self.render_mode_label)
        self.render_mode_box = QtWidgets.QComboBox(self.main_tab)
        self.render_mode_box.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.render_mode_box.sizePolicy().hasHeightForWidth())
        self.render_mode_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.render_mode_box.setFont(font)
        self.render_mode_box.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"")
        self.render_mode_box.setObjectName("render_mode_box")
        self.render_mode_box.addItem("")
        self.render_mode_box.addItem("")
        self.render_mode_box.addItem("")
        self.render_mode_box.addItem("")
        self.render_mode_box.addItem("")
        self.render_mode_Vlayout.addWidget(self.render_mode_box)
        self.render_control_Hlayout.addLayout(self.render_mode_Vlayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.render_control_Hlayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.render_control_Hlayout.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.render_control_Hlayout.addItem(spacerItem6)
        self.render_startstop_Vlayout = QtWidgets.QVBoxLayout()
        self.render_startstop_Vlayout.setObjectName("render_startstop_Vlayout")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_startstop_Vlayout.addItem(spacerItem7)
        self.render_start_button = QtWidgets.QPushButton(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.render_start_button.sizePolicy().hasHeightForWidth())
        self.render_start_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.render_start_button.setFont(font)
        self.render_start_button.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 3px;\n"
"border-top: 1px solid  rgb(37, 40, 44);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 2px solid  rgb(37, 40, 44);\n"
"font: 75 20pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-top: 1px solid  rgb(37, 40, 44);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 2px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 2px solid  rgb(37, 40, 44);\n"
"border-bottom: 1px solid  rgb(37, 40, 44);\n"
"padding-top: -5px;\n"
"}")
        self.render_start_button.setObjectName("render_start_button")
        self.render_startstop_Vlayout.addWidget(self.render_start_button)
        self.render_stop_button = QtWidgets.QPushButton(self.main_tab)
        self.render_stop_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.render_stop_button.sizePolicy().hasHeightForWidth())
        self.render_stop_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.render_stop_button.setFont(font)
        self.render_stop_button.setMouseTracking(False)
        self.render_stop_button.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 3px;\n"
"border-top: 1px solid  rgb(37, 40, 44);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 2px solid  rgb(37, 40, 44);\n"
"font: 75 20pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-top: 1px solid  rgb(37, 40, 44);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 2px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 2px solid  rgb(37, 40, 44);\n"
"border-bottom: 1px solid  rgb(37, 40, 44);\n"
"padding-top: -5px;\n"
"}")
        self.render_stop_button.setCheckable(False)
        self.render_stop_button.setObjectName("render_stop_button")
        self.render_startstop_Vlayout.addWidget(self.render_stop_button)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_startstop_Vlayout.addItem(spacerItem8)
        self.render_control_Hlayout.addLayout(self.render_startstop_Vlayout)
        self.gridLayout_2.addLayout(self.render_control_Hlayout, 4, 1, 1, 2)
        self.render_status_Vlayout = QtWidgets.QVBoxLayout()
        self.render_status_Vlayout.setObjectName("render_status_Vlayout")
        self.app_state_label = QtWidgets.QLabel(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_state_label.sizePolicy().hasHeightForWidth())
        self.app_state_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.app_state_label.setFont(font)
        self.app_state_label.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"\n"
"")
        self.app_state_label.setAlignment(QtCore.Qt.AlignCenter)
        self.app_state_label.setObjectName("app_state_label")
        self.render_status_Vlayout.addWidget(self.app_state_label)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_status_Vlayout.addItem(spacerItem9)
        self.elapsed_time_label = QtWidgets.QLabel(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elapsed_time_label.sizePolicy().hasHeightForWidth())
        self.elapsed_time_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.elapsed_time_label.setFont(font)
        self.elapsed_time_label.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"\n"
"")
        self.elapsed_time_label.setText("")
        self.elapsed_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.elapsed_time_label.setObjectName("elapsed_time_label")
        self.render_status_Vlayout.addWidget(self.elapsed_time_label)
        self.gridLayout_2.addLayout(self.render_status_Vlayout, 14, 1, 1, 2)
        self.render_progress_Vlayout = QtWidgets.QVBoxLayout()
        self.render_progress_Vlayout.setObjectName("render_progress_Vlayout")
        self.render_progress_bar = QtWidgets.QProgressBar(self.main_tab)
        self.render_progress_bar.setStyleSheet("QProgressBar {\n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 20px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{    \n"
"    border-radius: 20px;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.006, y1:0.556, x2:1, y2:0.522727, stop:0 rgba(54, 57, 63, 255), stop:1 rgba(54, 57, 63, 255));\n"
"}")
        self.render_progress_bar.setProperty("value", 0)
        self.render_progress_bar.setObjectName("render_progress_bar")
        self.render_progress_Vlayout.addWidget(self.render_progress_bar)
        self.gridLayout_2.addLayout(self.render_progress_Vlayout, 11, 1, 1, 2)
        self.render_inout_data_Hlayout = QtWidgets.QHBoxLayout()
        self.render_inout_data_Hlayout.setObjectName("render_inout_data_Hlayout")
        self.render_inout_paths_Vlayout = QtWidgets.QVBoxLayout()
        self.render_inout_paths_Vlayout.setObjectName("render_inout_paths_Vlayout")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_inout_paths_Vlayout.addItem(spacerItem10)
        self.audio_path_editline = QtWidgets.QLineEdit(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.audio_path_editline.sizePolicy().hasHeightForWidth())
        self.audio_path_editline.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.audio_path_editline.setFont(font)
        self.audio_path_editline.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"padding-bottom:7px;")
        self.audio_path_editline.setDragEnabled(True)
        self.audio_path_editline.setObjectName("audio_path_editline")
        self.render_inout_paths_Vlayout.addWidget(self.audio_path_editline)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_inout_paths_Vlayout.addItem(spacerItem11)
        self.raw_path_editline = QtWidgets.QLineEdit(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raw_path_editline.sizePolicy().hasHeightForWidth())
        self.raw_path_editline.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.raw_path_editline.setFont(font)
        self.raw_path_editline.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"padding-bottom:7px;")
        self.raw_path_editline.setDragEnabled(True)
        self.raw_path_editline.setObjectName("raw_path_editline")
        self.render_inout_paths_Vlayout.addWidget(self.raw_path_editline)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_inout_paths_Vlayout.addItem(spacerItem12)
        self.subtitle_path_editline = QtWidgets.QLineEdit(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtitle_path_editline.sizePolicy().hasHeightForWidth())
        self.subtitle_path_editline.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.subtitle_path_editline.setFont(font)
        self.subtitle_path_editline.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"padding-bottom:7px;")
        self.subtitle_path_editline.setDragEnabled(True)
        self.subtitle_path_editline.setObjectName("subtitle_path_editline")
        self.render_inout_paths_Vlayout.addWidget(self.subtitle_path_editline)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_inout_paths_Vlayout.addItem(spacerItem13)
        self.softsub_path_editline = QtWidgets.QLineEdit(self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.softsub_path_editline.sizePolicy().hasHeightForWidth())
        self.softsub_path_editline.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.softsub_path_editline.setFont(font)
        self.softsub_path_editline.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"padding-bottom:7px;")
        self.softsub_path_editline.setDragEnabled(True)
        self.softsub_path_editline.setObjectName("softsub_path_editline")
        self.render_inout_paths_Vlayout.addWidget(self.softsub_path_editline)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_inout_paths_Vlayout.addItem(spacerItem14)
        self.render_inout_data_Hlayout.addLayout(self.render_inout_paths_Vlayout)
        self.render_inout_buttons_Vlayout = QtWidgets.QVBoxLayout()
        self.render_inout_buttons_Vlayout.setObjectName("render_inout_buttons_Vlayout")
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_inout_buttons_Vlayout.addItem(spacerItem15)
        self.audio_path_open_button = QtWidgets.QPushButton(self.main_tab)
        self.audio_path_open_button.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.audio_path_open_button.setFont(font)
        self.audio_path_open_button.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 8pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-bottom: none;\n"
"padding-top: -5px;\n"
"}")
        self.audio_path_open_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/ICONS/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audio_path_open_button.setIcon(icon3)
        self.audio_path_open_button.setObjectName("audio_path_open_button")
        self.render_inout_buttons_Vlayout.addWidget(self.audio_path_open_button)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_inout_buttons_Vlayout.addItem(spacerItem16)
        self.raw_path_open_button = QtWidgets.QPushButton(self.main_tab)
        self.raw_path_open_button.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.raw_path_open_button.setFont(font)
        self.raw_path_open_button.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 8pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-bottom: none;\n"
"padding-top: -5px;\n"
"}color: rgb(205, 206, 208);")
        self.raw_path_open_button.setText("")
        self.raw_path_open_button.setIcon(icon3)
        self.raw_path_open_button.setObjectName("raw_path_open_button")
        self.render_inout_buttons_Vlayout.addWidget(self.raw_path_open_button)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_inout_buttons_Vlayout.addItem(spacerItem17)
        self.subtitle_path_open_button = QtWidgets.QPushButton(self.main_tab)
        self.subtitle_path_open_button.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.subtitle_path_open_button.setFont(font)
        self.subtitle_path_open_button.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 8pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-bottom: none;\n"
"padding-top: -5px;\n"
"}")
        self.subtitle_path_open_button.setText("")
        self.subtitle_path_open_button.setIcon(icon3)
        self.subtitle_path_open_button.setObjectName("subtitle_path_open_button")
        self.render_inout_buttons_Vlayout.addWidget(self.subtitle_path_open_button)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_inout_buttons_Vlayout.addItem(spacerItem18)
        self.softsub_path_open_button = QtWidgets.QPushButton(self.main_tab)
        self.softsub_path_open_button.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.softsub_path_open_button.setFont(font)
        self.softsub_path_open_button.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 8pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-bottom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-bottom: none;\n"
"padding-top: -5px;\n"
"}")
        self.softsub_path_open_button.setText("")
        self.softsub_path_open_button.setIcon(icon3)
        self.softsub_path_open_button.setObjectName("softsub_path_open_button")
        self.render_inout_buttons_Vlayout.addWidget(self.softsub_path_open_button)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.render_inout_buttons_Vlayout.addItem(spacerItem19)
        self.render_inout_data_Hlayout.addLayout(self.render_inout_buttons_Vlayout)
        self.gridLayout_2.addLayout(self.render_inout_data_Hlayout, 6, 1, 1, 2)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem20, 3, 1, 1, 2)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem21, 7, 1, 1, 2)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem22, 5, 1, 1, 2)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem23, 12, 1, 1, 2)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem24, 10, 1, 1, 2)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem25, 15, 1, 1, 2)
        self.app_tab.addTab(self.main_tab, "")
        self.folder_tab = QtWidgets.QWidget()
        self.folder_tab.setMouseTracking(True)
        self.folder_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.folder_tab.setAutoFillBackground(False)
        self.folder_tab.setObjectName("folder_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.folder_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.temp_label = QtWidgets.QLabel(self.folder_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.temp_label.setFont(font)
        self.temp_label.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"")
        self.temp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_label.setObjectName("temp_label")
        self.gridLayout.addWidget(self.temp_label, 0, 0, 1, 1)
        self.app_tab.addTab(self.folder_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.settings_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.settings_Vlayout = QtWidgets.QVBoxLayout()
        self.settings_Vlayout.setObjectName("settings_Vlayout")
        self.app_ffmpeg_update_check = QtWidgets.QCheckBox(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_ffmpeg_update_check.sizePolicy().hasHeightForWidth())
        self.app_ffmpeg_update_check.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.app_ffmpeg_update_check.setFont(font)
        self.app_ffmpeg_update_check.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.app_ffmpeg_update_check.setChecked(True)
        self.app_ffmpeg_update_check.setObjectName("app_ffmpeg_update_check")
        self.settings_Vlayout.addWidget(self.app_ffmpeg_update_check)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settings_Vlayout.addItem(spacerItem26)
        self.gridLayout_6.addLayout(self.settings_Vlayout, 0, 0, 1, 1)
        self.app_tab.addTab(self.settings_tab, "")
        self.whats_new_tab = QtWidgets.QWidget()
        self.whats_new_tab.setObjectName("whats_new_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.whats_new_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.version_history_browser = QtWidgets.QTextBrowser(self.whats_new_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.version_history_browser.setFont(font)
        self.version_history_browser.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.version_history_browser.setObjectName("version_history_browser")
        self.gridLayout_4.addWidget(self.version_history_browser, 0, 0, 1, 1)
        self.app_tab.addTab(self.whats_new_tab, "")
        self.dev_tab = QtWidgets.QWidget()
        self.dev_tab.setObjectName("dev_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.dev_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem27, 0, 1, 1, 1)
        self.dev_settings_Vlayout = QtWidgets.QVBoxLayout()
        self.dev_settings_Vlayout.setObjectName("dev_settings_Vlayout")
        self.dev_mode_enable = QtWidgets.QCheckBox(self.dev_tab)
        self.dev_mode_enable.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dev_mode_enable.sizePolicy().hasHeightForWidth())
        self.dev_mode_enable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.dev_mode_enable.setFont(font)
        self.dev_mode_enable.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.dev_mode_enable.setChecked(True)
        self.dev_mode_enable.setObjectName("dev_mode_enable")
        self.dev_settings_Vlayout.addWidget(self.dev_mode_enable)
        self.log_mode_enable = QtWidgets.QCheckBox(self.dev_tab)
        self.log_mode_enable.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_mode_enable.sizePolicy().hasHeightForWidth())
        self.log_mode_enable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.log_mode_enable.setFont(font)
        self.log_mode_enable.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.log_mode_enable.setChecked(True)
        self.log_mode_enable.setObjectName("log_mode_enable")
        self.dev_settings_Vlayout.addWidget(self.log_mode_enable)
        self.episodeline_autodetect_enable = QtWidgets.QCheckBox(self.dev_tab)
        self.episodeline_autodetect_enable.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.episodeline_autodetect_enable.sizePolicy().hasHeightForWidth())
        self.episodeline_autodetect_enable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.episodeline_autodetect_enable.setFont(font)
        self.episodeline_autodetect_enable.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.episodeline_autodetect_enable.setChecked(True)
        self.episodeline_autodetect_enable.setObjectName("episodeline_autodetect_enable")
        self.dev_settings_Vlayout.addWidget(self.episodeline_autodetect_enable)
        self.folders_autodetect_enable = QtWidgets.QCheckBox(self.dev_tab)
        self.folders_autodetect_enable.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folders_autodetect_enable.sizePolicy().hasHeightForWidth())
        self.folders_autodetect_enable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.folders_autodetect_enable.setFont(font)
        self.folders_autodetect_enable.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.folders_autodetect_enable.setChecked(False)
        self.folders_autodetect_enable.setObjectName("folders_autodetect_enable")
        self.dev_settings_Vlayout.addWidget(self.folders_autodetect_enable)
        self.gridLayout_5.addLayout(self.dev_settings_Vlayout, 0, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem28, 2, 0, 1, 1)
        self.app_tab.addTab(self.dev_tab, "")
        self.gridLayout_3.addWidget(self.app_tab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.app_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AniBaza converter"))
        self.episode_line.setPlaceholderText(_translate("MainWindow", "Название релиза ([AniBaza] Kaguya-sama Love is War TV [02])"))
        self.rickroll_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>asdasdasd</p></body></html>"))
        self.rickroll_button.setText(_translate("MainWindow", "AniBaza converter :3"))
        self.config_save_button.setText(_translate("MainWindow", "Сохранить конфигурацию"))
        self.FAQ_open_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline;\">А шо как делать? FAQ</span></p></body></html>"))
        self.FAQ_open_button.setText(_translate("MainWindow", " Инструкция тут "))
        self.anibaza_site_open_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>аыаыва</p></body></html>"))
        self.anibaza_site_open_button.setText(_translate("MainWindow", " На сайт "))
        self.hardsub_folder_open_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>аыаыва</p></body></html>"))
        self.hardsub_folder_open_button.setText(_translate("MainWindow", " Папка Hardsub "))
        self.app_version_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Version 2.4 (Einsein) by Miki-san</span></p></body></html>"))
        self.render_settings_label.setText(_translate("MainWindow", "Настройки"))
        self.logo_check.setText(_translate("MainWindow", "Лого"))
        self.soft_nvenc_check.setText(_translate("MainWindow", "Софт NVENC"))
        self.hard_nvenc_check.setText(_translate("MainWindow", "Хард NVENC"))
        self.render_mode_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Что собираем:</span></p></body></html>"))
        self.render_mode_box.setItemText(0, _translate("MainWindow", "Софт и хард"))
        self.render_mode_box.setItemText(1, _translate("MainWindow", "Только софт"))
        self.render_mode_box.setItemText(2, _translate("MainWindow", "Только хард"))
        self.render_mode_box.setItemText(3, _translate("MainWindow", "Для хардсабберов"))
        self.render_mode_box.setItemText(4, _translate("MainWindow", "Починить равку"))
        self.render_start_button.setText(_translate("MainWindow", "  НАЧАТЬ  "))
        self.render_stop_button.setText(_translate("MainWindow", " СТОП "))
        self.app_state_label.setText(_translate("MainWindow", "Заполняй поля!"))
        self.audio_path_editline.setPlaceholderText(_translate("MainWindow", "Дорожка звука"))
        self.raw_path_editline.setPlaceholderText(_translate("MainWindow", "Равка"))
        self.subtitle_path_editline.setPlaceholderText(_translate("MainWindow", "Файл субтитров"))
        self.softsub_path_editline.setPlaceholderText(_translate("MainWindow", "Путь сохранения софтсаба"))
        self.app_tab.setTabText(self.app_tab.indexOf(self.main_tab), _translate("MainWindow", "Один файл"))
        self.temp_label.setText(_translate("MainWindow", "БУДЕТ ЗАВТРА"))
        self.app_tab.setTabText(self.app_tab.indexOf(self.folder_tab), _translate("MainWindow", "Папка"))
        self.app_ffmpeg_update_check.setText(_translate("MainWindow", "Проверять обновления?"))
        self.app_tab.setTabText(self.app_tab.indexOf(self.settings_tab), _translate("MainWindow", "Настройки"))
        self.version_history_browser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Версия 2.5 (hotfix): </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Исправления:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">1) Исправлена проблема для заливов с файлами, размером более 1.8ГБ. Теперь создается два хардсаба где второй это более ужатый первый, который в свою очередь ограничен максимумом в 4 ГБ, для заливки в Телеграмм.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Переработано:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">1) Чуть снижена нагузка на слабые системы, за счет небольшого упрощения настроек рендера. Пока для всех. В будущих обновлениях настройки рендера будут зависеть от мощности целевой системы.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Добавлено:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">1) Добавлена возможность восстанавливать равки (HEVC -&gt; H264). Функция расположена в выпадающем списке. На вход нужна равка, путь сохранения, название выходного файла.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">2) Добавлен инструмент обновления FFmpeg. Работает по аналогии с обновлением основной программы и отключается поиск обнровлений той же галочкой в настройках.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Версия 2.1-2.4 (hotfix): </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Исправления:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: line-through;\">1) Исправлена проблема с ошибкой с отключенной галочкой sub. </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">(Убрано в процессе глобального фикса)</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">2) Исправлена проблема с ошибкой названия файла, содержащей дефис и квадратные скобки.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Переработано:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">1) Настройка битрейта заменена на настройку CRF (вшитая настройка, </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline;\">не настраиваемая</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">2) Система логгирования ошибок (временно включено по умолчанию на все время бета тестирования).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Добавлено:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">1) Система обновлений программы (экспериментально, </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline;\">есть возможность отключения</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">2) Настройка скорости рендера (экспериментально, </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline;\">не настраиваемая</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">3) Настройка специфичного рендера анимации (вшитая настройка, экспериментально).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">4) Настройка битности и цветового диапазона (вшитая настройка, экспериментально).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">5) Автоматическая настройка битности и диапазона цвета по предварительному исследованию оригинала (экспериментально).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">6) Расчет оставшегося времени рендера в прогресс баре. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Версия 2.0 (Einstein): </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; text-decoration: underline;\">Глобальная переработка движка программы.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Исправления:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">1) Исправлен баг приводящий к критической ошибке если в названии субтитров были квадратные скобки.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">2) Исправлен баг с неработающей кнопкой sub для рендера без субтитров.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">3) При выборе места сохранения софтсаба если папка удовлетворяет стандартному шаблону названий папок торрентов, то автоматически будет сгенерировано название серии, где нужно будет только написать номер.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">4) Мелкие технические исправления.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Добавлено:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">1) Добавлена вкладка &quot;Настройки&quot; для будущей кастомизации работы с программой.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">2) Добавлена вкладка &quot;Для разработчика&quot; для тестирования новых экспериментальных функций, а также для активации специфических режимов работы.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">3) Добавлена галочка &quot;Лого&quot; для того чтобы добавить лого Анибазы при рендере.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">4) Добавлена галочка &quot;HEVC&quot; для рендера хардсаба в кодеке h265 (он же HEVC).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">5) При первом запуске программы будет автоматически скачан и установлен ffmpeg, а также шрифты для работы с Лого.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Версия 1.3 (Fresco): </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline;\">Версию считать тупиковой и нерабочей!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Версия 1.2 (Euclid): </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Частичная переработка движка программы и исправление мелких багов.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Версия 1.1 (Newton): </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Исправления:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">1) Исправлена проблема с доступом к правам администратора. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">2) Исправлен баг с вылетом программы при отсутствии папки HARDSUB.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Добавлено:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">1) Добавлена вкладка &quot;Что нового?&quot; для отображения всех изменений в текущей версии.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">2) При отсутствии установленного ffmpeg, автоматически переносит необходимые для работы файлы в системную папку и прописывает путь в переменных среды компьютера.</span></p></body></html>"))
        self.app_tab.setTabText(self.app_tab.indexOf(self.whats_new_tab), _translate("MainWindow", "Что нового?"))
        self.dev_mode_enable.setText(_translate("MainWindow", "Включить режим разработчика"))
        self.log_mode_enable.setText(_translate("MainWindow", "Записывать лог файлы (Экспериментальное)"))
        self.episodeline_autodetect_enable.setText(_translate("MainWindow", "Автодетектинг названия тайтла по торрент папке (Экспериментальное)"))
        self.folders_autodetect_enable.setText(_translate("MainWindow", "Автодетектинг папок (Экспериментальное)"))
        self.app_tab.setTabText(self.app_tab.indexOf(self.dev_tab), _translate("MainWindow", "Для разработчика"))
import resourses_rc
