# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'normUI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 589)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("selection-color: rgb(255, 255, 255);")
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("background-color: rgb(54, 57, 63);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.app_tab = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.app_tab.setFont(font)
        self.app_tab.setMouseTracking(False)
        self.app_tab.setStyleSheet("\n"
"QTabBar::tab, \n"
"QTabBar::tab:hover\n"
"{\n"
"border: 1px solid rgba(105, 118, 132, 255);\n"
"selection-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(98, 114, 164);\n"
"background-color: rgb(47, 49, 54);\n"
"}\n"
"\n"
"")
        self.app_tab.setElideMode(QtCore.Qt.ElideLeft)
        self.app_tab.setDocumentMode(True)
        self.app_tab.setTabsClosable(False)
        self.app_tab.setMovable(False)
        self.app_tab.setObjectName("app_tab")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.main_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_tab.setStyleSheet("background-color: rgb(54, 57, 63);")
        self.main_tab.setObjectName("main_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 3, 1, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.episodeLine = QtWidgets.QLineEdit(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.episodeLine.setFont(font)
        self.episodeLine.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"padding-bottom:7px;")
        self.episodeLine.setObjectName("episodeLine")
        self.verticalLayout_3.addWidget(self.episodeLine)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 7, 1, 1, 4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.faqButton = QtWidgets.QPushButton(self.main_tab)
        self.faqButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.faqButton.setFont(font)
        self.faqButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 5px;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 12pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-buttom: none;\n"
"padding-top: -5px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/ICONS/faq_question_icon_149479.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.faqButton.setIcon(icon)
        self.faqButton.setObjectName("faqButton")
        self.horizontalLayout.addWidget(self.faqButton)
        self.siteButton = QtWidgets.QPushButton(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.siteButton.setFont(font)
        self.siteButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 5px;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 12pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-buttom: none;\n"
"padding-top: -5px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/ICONS/web_120072.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.siteButton.setIcon(icon1)
        self.siteButton.setObjectName("siteButton")
        self.horizontalLayout.addWidget(self.siteButton)
        self.hardfolderButton = QtWidgets.QPushButton(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.hardfolderButton.setFont(font)
        self.hardfolderButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 5px;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 12pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-buttom: none;\n"
"padding-top: -5px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/ICONS/folder_storage_file_icon_193553.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hardfolderButton.setIcon(icon2)
        self.hardfolderButton.setObjectName("hardfolderButton")
        self.horizontalLayout.addWidget(self.hardfolderButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 15, 1, 2, 4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.versionLabel = QtWidgets.QLabel(self.main_tab)
        self.versionLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionLabel.sizePolicy().hasHeightForWidth())
        self.versionLabel.setSizePolicy(sizePolicy)
        self.versionLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.versionLabel.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.versionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.versionLabel.setWordWrap(False)
        self.versionLabel.setObjectName("versionLabel")
        self.verticalLayout_4.addWidget(self.versionLabel)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 17, 1, 1, 4)
        self.pushButton_rick = QtWidgets.QPushButton(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_rick.setFont(font)
        self.pushButton_rick.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.pushButton_rick.setObjectName("pushButton_rick")
        self.gridLayout_2.addWidget(self.pushButton_rick, 0, 1, 2, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stateLabel = QtWidgets.QLabel(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.stateLabel.setFont(font)
        self.stateLabel.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"\n"
"")
        self.stateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stateLabel.setObjectName("stateLabel")
        self.horizontalLayout_3.addWidget(self.stateLabel)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 13, 1, 1, 4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.progressBar = QtWidgets.QProgressBar(self.main_tab)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 20px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{    \n"
"    border-radius: 20px;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.006, y1:0.556, x2:1, y2:0.522727, stop:0 rgba(54, 57, 63, 255), stop:1 rgba(54, 57, 63, 255));\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_8.addWidget(self.progressBar)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 10, 1, 1, 4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.logo_check = QtWidgets.QCheckBox(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.logo_check.setFont(font)
        self.logo_check.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.logo_check.setChecked(True)
        self.logo_check.setObjectName("logo_check")
        self.verticalLayout_12.addWidget(self.logo_check)
        self.nvencCheck = QtWidgets.QCheckBox(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nvencCheck.setFont(font)
        self.nvencCheck.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.nvencCheck.setChecked(False)
        self.nvencCheck.setObjectName("nvencCheck")
        self.verticalLayout_12.addWidget(self.nvencCheck)
        self.codec = QtWidgets.QCheckBox(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.codec.setFont(font)
        self.codec.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;")
        self.codec.setObjectName("codec")
        self.verticalLayout_12.addWidget(self.codec)
        self.hardCheck = QtWidgets.QCheckBox(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hardCheck.setFont(font)
        self.hardCheck.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.hardCheck.setChecked(True)
        self.hardCheck.setObjectName("hardCheck")
        self.verticalLayout_12.addWidget(self.hardCheck)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.modeLabel = QtWidgets.QLabel(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.modeLabel.setFont(font)
        self.modeLabel.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.modeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.modeLabel.setObjectName("modeLabel")
        self.verticalLayout_11.addWidget(self.modeLabel)
        self.modeBox = QtWidgets.QComboBox(self.main_tab)
        self.modeBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.modeBox.setFont(font)
        self.modeBox.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"")
        self.modeBox.setObjectName("modeBox")
        self.modeBox.addItem("")
        self.modeBox.addItem("")
        self.modeBox.addItem("")
        self.modeBox.addItem("")
        self.verticalLayout_11.addWidget(self.modeBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem5)
        self.bitrateLabel = QtWidgets.QLabel(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bitrateLabel.setFont(font)
        self.bitrateLabel.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.bitrateLabel.setObjectName("bitrateLabel")
        self.verticalLayout_10.addWidget(self.bitrateLabel)
        self.bitrateBox = QtWidgets.QComboBox(self.main_tab)
        self.bitrateBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bitrateBox.setFont(font)
        self.bitrateBox.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"")
        self.bitrateBox.setObjectName("bitrateBox")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.bitrateBox.addItem("")
        self.verticalLayout_10.addWidget(self.bitrateBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.startButton = QtWidgets.QPushButton(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 5px;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 20pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-buttom: none;\n"
"padding-top: -5px;\n"
"}")
        self.startButton.setObjectName("startButton")
        self.verticalLayout_9.addWidget(self.startButton)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.stopButton = QtWidgets.QPushButton(self.main_tab)
        self.stopButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.stopButton.setFont(font)
        self.stopButton.setMouseTracking(False)
        self.stopButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 5px;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 20pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-buttom: none;\n"
"padding-top: -5px;\n"
"}")
        self.stopButton.setCheckable(False)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout_9.addWidget(self.stopButton)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 1, 1, 4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.soundPath = QtWidgets.QLineEdit(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.soundPath.setFont(font)
        self.soundPath.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"padding-bottom:7px;")
        self.soundPath.setDragEnabled(True)
        self.soundPath.setObjectName("soundPath")
        self.verticalLayout.addWidget(self.soundPath)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.rawPath = QtWidgets.QLineEdit(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.rawPath.setFont(font)
        self.rawPath.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"padding-bottom:7px;")
        self.rawPath.setDragEnabled(True)
        self.rawPath.setObjectName("rawPath")
        self.verticalLayout.addWidget(self.rawPath)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.subPath = QtWidgets.QLineEdit(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.subPath.setFont(font)
        self.subPath.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"padding-bottom:7px;")
        self.subPath.setDragEnabled(True)
        self.subPath.setObjectName("subPath")
        self.verticalLayout.addWidget(self.subPath)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.softPath = QtWidgets.QLineEdit(self.main_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.softPath.setFont(font)
        self.softPath.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"padding-bottom:7px;")
        self.softPath.setDragEnabled(True)
        self.softPath.setObjectName("softPath")
        self.verticalLayout.addWidget(self.softPath)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem15)
        self.soundButton = QtWidgets.QPushButton(self.main_tab)
        self.soundButton.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.soundButton.setFont(font)
        self.soundButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 5px;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 8pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-buttom: none;\n"
"padding-top: -5px;\n"
"}")
        self.soundButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/ICONS/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.soundButton.setIcon(icon3)
        self.soundButton.setObjectName("soundButton")
        self.verticalLayout_2.addWidget(self.soundButton)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem16)
        self.rawButton = QtWidgets.QPushButton(self.main_tab)
        self.rawButton.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.rawButton.setFont(font)
        self.rawButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 5px;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 8pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-buttom: none;\n"
"padding-top: -5px;\n"
"}color: rgb(205, 206, 208);")
        self.rawButton.setText("")
        self.rawButton.setIcon(icon3)
        self.rawButton.setObjectName("rawButton")
        self.verticalLayout_2.addWidget(self.rawButton)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem17)
        self.subButton = QtWidgets.QPushButton(self.main_tab)
        self.subButton.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.subButton.setFont(font)
        self.subButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 5px;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 8pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-buttom: none;\n"
"padding-top: -5px;\n"
"}")
        self.subButton.setText("")
        self.subButton.setIcon(icon3)
        self.subButton.setObjectName("subButton")
        self.verticalLayout_2.addWidget(self.subButton)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem18)
        self.softButton = QtWidgets.QPushButton(self.main_tab)
        self.softButton.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.softButton.setFont(font)
        self.softButton.setStyleSheet("QPushButton{\n"
"border: none;\n"
"padding-top: 5px;\n"
"padding-top: 3px;\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"font: 75 8pt \"Segoe UI\";\n"
"color: rgb(98, 114, 164);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(62, 65, 72);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-buttom: 3px solid  rgb(37, 40, 44);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(44, 47, 52);\n"
"border-left: 1px solid  rgb(37, 40, 44);\n"
"border-right: 1px solid  rgb(37, 40, 44);\n"
"border-top: 3px solid  rgb(37, 40, 44);\n"
"border-buttom: none;\n"
"padding-top: -5px;\n"
"}")
        self.softButton.setText("")
        self.softButton.setIcon(icon3)
        self.softButton.setObjectName("softButton")
        self.verticalLayout_2.addWidget(self.softButton)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem19)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 5, 1, 1, 4)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem20, 11, 1, 1, 4)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem21, 14, 1, 1, 4)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem22, 9, 1, 1, 4)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem23, 6, 1, 1, 4)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem24, 4, 1, 1, 4)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem25, 2, 1, 1, 4)
        self.app_tab.addTab(self.main_tab, "")
        self.folder_tab = QtWidgets.QWidget()
        self.folder_tab.setMouseTracking(True)
        self.folder_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.folder_tab.setAutoFillBackground(False)
        self.folder_tab.setObjectName("folder_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.folder_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.tempLabel = QtWidgets.QLabel(self.folder_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.tempLabel.setFont(font)
        self.tempLabel.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"")
        self.tempLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tempLabel.setObjectName("tempLabel")
        self.gridLayout.addWidget(self.tempLabel, 0, 0, 1, 1)
        self.app_tab.addTab(self.folder_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.settings_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.settings_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.app_tab.addTab(self.settings_tab, "")
        self.whatsnew_tab = QtWidgets.QWidget()
        self.whatsnew_tab.setObjectName("whatsnew_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.whatsnew_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.whatsnew_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_4.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.app_tab.addTab(self.whatsnew_tab, "")
        self.dev_tab = QtWidgets.QWidget()
        self.dev_tab.setObjectName("dev_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.dev_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem26, 0, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.enableDevMode = QtWidgets.QCheckBox(self.dev_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.enableDevMode.setFont(font)
        self.enableDevMode.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.enableDevMode.setObjectName("enableDevMode")
        self.verticalLayout_5.addWidget(self.enableDevMode)
        self.folderAutodecting = QtWidgets.QCheckBox(self.dev_tab)
        self.folderAutodecting.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.folderAutodecting.setFont(font)
        self.folderAutodecting.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.folderAutodecting.setObjectName("folderAutodecting")
        self.verticalLayout_5.addWidget(self.folderAutodecting)
        self.videoBitrateAutodetectibg = QtWidgets.QCheckBox(self.dev_tab)
        self.videoBitrateAutodetectibg.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.videoBitrateAutodetectibg.setFont(font)
        self.videoBitrateAutodetectibg.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.videoBitrateAutodetectibg.setObjectName("videoBitrateAutodetectibg")
        self.verticalLayout_5.addWidget(self.videoBitrateAutodetectibg)
        self.enableLogging = QtWidgets.QCheckBox(self.dev_tab)
        self.enableLogging.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.enableLogging.setFont(font)
        self.enableLogging.setStyleSheet("color: rgb(98, 114, 164);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"border:none;\n"
"")
        self.enableLogging.setObjectName("enableLogging")
        self.verticalLayout_5.addWidget(self.enableLogging)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem27, 2, 0, 1, 1)
        self.app_tab.addTab(self.dev_tab, "")
        self.gridLayout_3.addWidget(self.app_tab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.app_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AniBaza converter"))
        self.episodeLine.setPlaceholderText(_translate("MainWindow", "Название релиза ([AniBaza] Kaguya-sama Love is War TV [02])"))
        self.faqButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline;\">А шо как делать? FAQ</span></p></body></html>"))
        self.faqButton.setText(_translate("MainWindow", " Инструкция тут "))
        self.siteButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>аыаыва</p></body></html>"))
        self.siteButton.setText(_translate("MainWindow", " На сайт "))
        self.hardfolderButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>аыаыва</p></body></html>"))
        self.hardfolderButton.setText(_translate("MainWindow", " Папка Hardsub "))
        self.versionLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Version 2.0 (Einsein) by Miki-san</span></p></body></html>"))
        self.pushButton_rick.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>asdasdasd</p></body></html>"))
        self.pushButton_rick.setText(_translate("MainWindow", "AniBaza converter <- click here :3"))
        self.stateLabel.setText(_translate("MainWindow", "Заполняй поля!"))
        self.logo_check.setText(_translate("MainWindow", "Лого"))
        self.nvencCheck.setText(_translate("MainWindow", "Nvenc"))
        self.codec.setText(_translate("MainWindow", "HEVC"))
        self.hardCheck.setText(_translate("MainWindow", "Sub"))
        self.modeLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Что собираем:</span></p></body></html>"))
        self.modeBox.setItemText(0, _translate("MainWindow", "Софт и хард"))
        self.modeBox.setItemText(1, _translate("MainWindow", "Только софт"))
        self.modeBox.setItemText(2, _translate("MainWindow", "Только хард"))
        self.modeBox.setItemText(3, _translate("MainWindow", "Для хардсабберов"))
        self.bitrateLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Битрейт</span>, kbps:</p></body></html>"))
        self.bitrateBox.setItemText(0, _translate("MainWindow", "1000"))
        self.bitrateBox.setItemText(1, _translate("MainWindow", "1500"))
        self.bitrateBox.setItemText(2, _translate("MainWindow", "2000"))
        self.bitrateBox.setItemText(3, _translate("MainWindow", "2500"))
        self.bitrateBox.setItemText(4, _translate("MainWindow", "3000"))
        self.bitrateBox.setItemText(5, _translate("MainWindow", "3500"))
        self.bitrateBox.setItemText(6, _translate("MainWindow", "4000"))
        self.bitrateBox.setItemText(7, _translate("MainWindow", "4500"))
        self.bitrateBox.setItemText(8, _translate("MainWindow", "5000"))
        self.bitrateBox.setItemText(9, _translate("MainWindow", "5500"))
        self.bitrateBox.setItemText(10, _translate("MainWindow", "6000"))
        self.bitrateBox.setItemText(11, _translate("MainWindow", "6500"))
        self.bitrateBox.setItemText(12, _translate("MainWindow", "7000"))
        self.bitrateBox.setItemText(13, _translate("MainWindow", "7500"))
        self.bitrateBox.setItemText(14, _translate("MainWindow", "8000"))
        self.bitrateBox.setItemText(15, _translate("MainWindow", "9000"))
        self.bitrateBox.setItemText(16, _translate("MainWindow", "10000"))
        self.bitrateBox.setItemText(17, _translate("MainWindow", "11000"))
        self.bitrateBox.setItemText(18, _translate("MainWindow", "12000"))
        self.startButton.setText(_translate("MainWindow", "  НАЧАТЬ  "))
        self.stopButton.setText(_translate("MainWindow", " СТОП "))
        self.soundPath.setPlaceholderText(_translate("MainWindow", "Дорожка звука"))
        self.rawPath.setPlaceholderText(_translate("MainWindow", "Равка"))
        self.subPath.setPlaceholderText(_translate("MainWindow", "Файл субтитров"))
        self.softPath.setPlaceholderText(_translate("MainWindow", "Путь сохранения софтсаба"))
        self.app_tab.setTabText(self.app_tab.indexOf(self.main_tab), _translate("MainWindow", "Один файл"))
        self.tempLabel.setText(_translate("MainWindow", "БУДЕТ ЗАВТРА"))
        self.app_tab.setTabText(self.app_tab.indexOf(self.folder_tab), _translate("MainWindow", "Папка"))
        self.label.setText(_translate("MainWindow", "БУДЕТ ЗАВТРА"))
        self.app_tab.setTabText(self.app_tab.indexOf(self.settings_tab), _translate("MainWindow", "Настройки"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Версия 2.0 (Einstein): </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; text-decoration: underline;\">Глобальная переработка движка программы.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Исправления:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">1) Исправлен баг приводящий к критической ошибке если в названии субтитров были квадратные скобки.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">2) Исправлен баг с неработающей кнопкой sub для рендера без субтитров.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">3) При выборе места сохранения софтсаба если папка удовлетворяет стандартному шаблону названий папок торрентов, то автоматически будет сгенерировано название серии, где нужно будет только написать номер.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">4) Мелкие технические исправления.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Добавлено:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">1) Добавлена вкладка &quot;Настройки&quot; для будущей кастомизации работы с программой.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">2) Добавлена вкладка &quot;Для разработчика&quot; для тестирования новых экспериментальных функций, а также для активации специфических режимов работы.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">3) Добавлена галочка &quot;Лого&quot; для того чтобы добавить лого Анибазы при рендере.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">4) Добавлена галочка &quot;HEVC&quot; для рендера хардсаба в кодеке h265 (он же HEVC).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">5) При первом запуске программы будет автоматически скачан и установлен ffmpeg, а также шрифты для работы с Лого.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Версия 1.3 (Fresco): </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; text-decoration: underline;\">Версию считать тупиковой и нерабочей!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Версия 1.2 (Euclid): </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Частичная переработка движка программы и исправление мелких багов.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600;\">Версия 1.1 (Newton): </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Исправления:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">1) Исправлена проблема с доступом к правам администратора. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">2) Исправлен баг с вылетом программы при отсутствии папки HARDSUB.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Добавлено:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">1) Добавлена вкладка &quot;Что нового?&quot; для отображения всех изменений в текущей версии.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">2) При отсутствии установленного ffmpeg, автоматически переносит необходимые для работы файлы в системную папку и прописывает путь в переменных среды компьютера.</span></p></body></html>"))
        self.app_tab.setTabText(self.app_tab.indexOf(self.whatsnew_tab), _translate("MainWindow", "Что нового?"))
        self.enableDevMode.setText(_translate("MainWindow", "Включить режим разработчика"))
        self.folderAutodecting.setText(_translate("MainWindow", "Автодетектинг папок (Экспериментальное)"))
        self.videoBitrateAutodetectibg.setText(_translate("MainWindow", "Автодетектинг битрейта видео для хардсаба (Экспериментальное)"))
        self.enableLogging.setText(_translate("MainWindow", "Записывать лог файлы (Экспериментальное)"))
        self.app_tab.setTabText(self.app_tab.indexOf(self.dev_tab), _translate("MainWindow", "Для разработчика"))
import resourses_rc
